// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unaxditvboqzhdlximwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuYXhkaXR2Ym9xemhkbHhpbXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzAyMTksImV4cCI6MjA2OTQ0NjIxOX0.qvZ63SZ0r00qUNnJlfyR7u2BVI_fDi06xpgSuAtINGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});